# Generated by Django 4.1 on 2022-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_key',
            field=models.CharField(default='0', max_length=32),
            preserve_default=False,
        ),
    ]
